### ISSUE TITLE
WebResource.axd is blank

### ISSUE THREAD

**Issue by joero4** [turquoiseowl/i18n#255]
Hello, I'm running version 2.1.6 form nuget, and our WebResource.axd file is blank.  I read that you fixed the problem back in April, but I'm still seeing the issue. 

Thanks,
Joe

**Comment by turquoiseowl** [comment]
@gitsno May I defer to you on this?

@joero4 As a fallback, have you tried adding the .axd resources to the ```i18n.LocalizedApplication.Current.UrlsToExcludeFromProcessing``` regex?

Ref: #193

**Comment by joero4** [comment]
i18n.LocalizedApplication.Current.UrlsToExcludeFromProcessing = new Regex("(?:\.(?:less|css|js|axd)(?:\?|$))|(?i:i18nSkip|glimpse|trace|elmah)")

This is our setting right now.  Is this correct?

Thanks,
Joe

**Comment by turquoiseowl** [comment]
That should match ```.axd``` okay, although you might escape the first period with a backslash.

Are you saying with that set, the ```.axd``` resources are being modified by i18n?

If so, short of help from @gitsno or someone else who has got it to work in your environment, I can only suggest referencing a local build of i18n from your project and debugging a request to see what's going on. There is quite a lot of trace output in the debug build, and I would suggest putting breakpoints in the event handlers in i18n.LocalizingModule, in particular OnPostRequestHandlerExecute.

**Comment by joero4** [comment]
Strange, the copy paste must have striped the backslash, it's there in my code.

To be exact the WebResource.axd file is coming back blank.  We have 3 other ScriptResource.axd files which are fine.  It's only the WebResource.axd file that is affected.  

Thanks,
Joe

**Comment by turquoiseowl** [comment]
There is a direct reference to ```/webresource.axd``` in ```LocalizingModule.OnPostRequestHandlerExecute```, but not to any other axd files. This may be why ScriptResource.axd is okay, but webresource.axd is not.

An avenue would be to remove that code yourself and see if that makes a difference.

**Comment by turquoiseowl** [comment]
No response so closing. Feel free to re-open with further comment.

**Comment by gitsno** [comment]
Sorry for not replying sooner, the notifications about this issue were blocked in my spam filter. The fix I made last year was specifically for webresource.axd, (not scriptresource.axd) because as far as I could tell the issue only affects webresource.axd - I have never seen it happen with scriptresource.axd. As I note in my comments for the fix I exclude both files from i18n processing anyway - here's my exclusion regex, yours seems OK, but mine is different so maybe try this (all one line from my global.asax Application_Start):

`            i18n.LocalizedApplication.Current.UrlsToExcludeFromProcessing = new System.Text.RegularExpressions.Regex(@"(?:\.(?:less|css|js)(?:\?|$))|(?i:i18nSkip|glimpse|trace|elmah|ScriptResource\.axd|WebResource\.axd)");
`
