### ISSUE TITLE
Content of .js files not translated

### ISSUE THREAD

**Issue by sandrulini** [turquoiseowl/i18n#270]
if I put a nugget in javascript function inside cshtml it works well, but nuggets inside .js files are not translated.

**Comment by kblok** [comment]
@sandrulini the problem is that IIS treats javascript files as static files, because they are, in fact, static files. so those files are not being processed by ASP.NET ergo, no translation is being perform.

I wrote a file translator which generate /en /es /foo /bar folders with translated javascripts so then you add the file you need in the website

**Comment by turquoiseowl** [comment]
i18n supports javascript okay although static file compression needs to be disabled. See:

https://github.com/turquoiseowl/i18n#static-file-compression-and-i18n

**Comment by sandrulini** [comment]
Ok, understood! thanks
