### ISSUE TITLE
.net 8 Compatible

### ISSUE THREAD

**Issue by jegadjame** [turquoiseowl/i18n#425]
I am trying to implement it in .net which has appsettings.json instead of web.config.. Will this work for .net 8

**Comment by turquoiseowl** [comment]
i18n supports NET Framework, not .NET Core I’m afraid.

From: jegadjame ***@***.***>
Sent: 05 June 2024 12:29
To: turquoiseowl/i18n ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [turquoiseowl/i18n] .net 8 Compatible (Issue #425)


I am trying to implement it in .net which has appsettings.json instead of web.config.. Will this work for .net 8

**Comment by jegadjame** [comment]
Thank you
